-- M5: Add missing AuditAction and AuditEntityType enum values for transaction audit trail

-- Add JOURNAL_ENTRY_* values to AuditAction enum
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'JOURNAL_ENTRY_CREATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'JOURNAL_ENTRY_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'JOURNAL_ENTRY_POSTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'JOURNAL_ENTRY_REVERSED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'JOURNAL_ENTRY_VOIDED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'JOURNAL_ENTRY_SUBMITTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'JOURNAL_ENTRY_APPROVED';

-- Add JOURNAL_ENTRY to AuditEntityType enum
ALTER TYPE "AuditEntityType" ADD VALUE IF NOT EXISTS 'JOURNAL_ENTRY';